name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15'
        otp-version: '26'
    
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Build escript
      run: mix escript.build
    
    - name: Verify escript was created
      run: |
        if [ ! -f nerves_burner ]; then
          echo "Error: nerves_burner executable not found"
          exit 1
        fi
        echo "✓ Escript built successfully"
        ls -lh nerves_burner
    
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        files: nerves_burner
        fail_on_unmatched_files: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
